config/routes.rb
MessagingApp::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    get 'users/buy_credits' => 'users#buy_credits', as: :buy_credits
    post 'users/update_credits' => 'users#update_credits', as: :update_credits
  end
  

  resources :messages

  root 'messages#index'

  

end

app/models/message.rb
class Message < ActiveRecord::Base

  # include ActiveModel::Validations
  # include ActiveModel::Conversion
  # extend ActiveModel::Naming

  # attr_accessor :phone, :body

  validates :phone, presence: true
  validates :body, presence: true
  
  # def initialize(attributes = {})
  #   return false if attributes.blank?
  #   attributes.each do |name,value|
  #     send("#{name}=", value)
  #   end
  # end

  def send_message
    number_to_send_to = phone
    twilio_sid = 'ACaf6af8863d70c2c6aa4c77579e7bced6'
    twilio_token ='c5251c8b4e84b6e0ae478cb4712bd391'
    twilio_phone_number = '1903683040'

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    @twilio_client.account.sms.messages.create(
      :from => "+44#{twilio_phone_number}",
      :to => phone,
      :body => body
      )
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_credits?
    credits > 0
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :credits)
    end
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  
  def new

    @cart = params[]
    @amount = cart.total

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => current_user.id,
      :amount      => @amount,
      :description => 'Twilio Stripe customer',
      :currency    => 'gbp'
    )


    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to '/'  
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index]

  def index
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message].permit(:phone, :body))

    if @message.valid?
      @message.send_message
      flash[:notice] = 'Message sent'
      redirect_to '/'
    else
      render 'index'     
    end
  end

  
  # rescue Message::SendFailure
  #   flash[:error] = 'Something went wrong'
  #   redirect_to '/'
  # end

end

app/controllers/receive_messages_controller.rb
class ReceiveMessagesController < ApplicationController

  def index
    message_body = params['Body']
    from_number = params['From']

    SMSLogger.log_text_message from_number message_body
  end

end

app/controllers/send_messages_controller.rb
class SendMessagesController < ApplicationController

  def index
    @message = Message.new
  end

  def send
    number_to_send_to = params[:phone]
    twilio_sid = ENV['TWILIO_SID']
    twilio_token = ENV['TWILIO_TOKEN']
    twilio_Phone_number = ENV['TWILIO_PHONE_NUMBER']
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => "Twilio message to be sent to #{number_to_send_to}"
      )

    flash.notice = 'Your message has been sent'
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::SessionsController
 
  def buy_credits

  end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/receive_messages_helper.rb
module ReceiveMessagesHelper
end

app/helpers/send_messages_helper.rb
module SendMessagesHelper
end

app/views/credits/new.html.haml
= form_tag cart_charges_path do
  %article
    %label{class: 'amount'}
      %span amount: = number_to_currency current_cart.total, unit: '£' 


%script{src: "https://checkout.stripe.com/v2/checkout.js", class: "stripe-button", data-key=: "= Rails.configuration.stripe[:publishable_key]", data-description: "A month's subscription", data-amount:= number_to_currency current_cart.total * 100, unit: '£'

%script{:type => "text/javascript",
        :src  => "javascripts/script_#{2 + 7}"}

app/views/layouts/_header.html.haml
%header
  #user-links
    - if user_signed_in? 
      Credits:
      = user.credits
      = link_to 'Buy Credits', buy_credits_path, class: 'button'
      = link_to 'Sign out', destroy_user_session_path, class: 'button'
    - else
      = link_to 'Sign up', new_user_registration_path, class: 'button'
      = link_to 'Sign in', user_session_path, class: 'button'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messaging App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render(partial: 'layouts/header', :locals => {:user => current_user}) %>
<div class='container'>
  <% if flash[:notice] %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if flash[:alert] %>
    <p class="alert"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_form.html.haml
- if current_user.has_credits?
  = form_for Message.new, url: messages_path do |f|
    %p
      = f.label 'phone', 'Phone number to send message to'
      = f.text_field 'phone'  
    %p
      = f.label 'body', 'Message'
      = f.text_area 'body'
    = f.submit 'Send message', class: 'button'
- else
  %h3
    You must have credits to send a message. Please use the link above to purchase credits.

app/views/messages/index.html.haml
.form-border
  .form-container
    - if @message.errors.any?
      = render partial: 'shared/error_messages'
    - if user_signed_in?
      = render partial: 'form'
    - else
      %h3
        You must be signed in and have credits to send a message.

app/views/shared/_error_messages.html.haml
.errors
  %h3
    = pluralize(@message.errors.count, 'error')
    prohibited this message from being sent:
  %ul
    - @message.errors.full_messages.each do |message|
      %li= message

app/views/users/buy_credits.html.haml
.form-container
  / - if @message.errors.any?
  /   = render partial: 'shared/error_messages'

  %h3 Buy Credits
  = form_tag current_user.update_credits, update_credits_path do |f|
    %p
      = f.label 'credits', 'Number of credits'
      = f.text_field 'credits'  
    %p
      = f.label 'credit_card', 'Credit card number'
      = f.text_field 'credit_card'
    = f.submit 'Buy Credits', class: 'button'

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>